title = "The Recipe Project"
baseURL = 'https://therecipeproject.net/'
languageCode = 'en-us'
theme = "ananke"

enableRobotsTXT = true

[outputs]
	home=["HTML","JSON"]
[taxinomies]
	tag="tags"

[params]
	description = "Recipes Fast."
	editOnGithubPath = "https://github.com/ConnorWorrell/RecipeProjectSite/blob/master/content/"

[menu]
[[menu.main]]
	identifier = "Search"
	name = "Search"
	url = "/search/"
	weight = 0
[[menu.main]]
	identifier = "Tags"
	name = "Tags"
	url = "/tags/"
	weight = -10
